package com.plnt.client.core

/**
 * Single seam between this app and the UniFFI-generated `uniffi.plnt_core.*`
 * symbols (app/app/src/main/kotlin/com/plnt/client/uniffi/plnt_core/plnt_core.kt).
 *
 * That file is regenerated by build.sh from core/src/plnt_core.udl + the
 * #[uniffi::export] macros in core/src/lib.rs and is NOT checked in in its
 * post-PHA-3075 form in this workspace snapshot — it still only exports
 * `coreVersion()`. Exact Kotlin-side casing/nullability of generated members
 * (e.g. u64 -> ULong vs Long) can shift between uniffi-bindgen versions, so
 * every direct reference to a generated symbol lives in this one file. If a
 * real build fails here, this is the only file that needs adjusting.
 */
sealed class CoreEvent {
    data class Connected(val ownClientId: Long, val serverName: String) : CoreEvent()
    data class Disconnected(val reason: String) : CoreEvent()
    data class ChannelTree(val channels: List<CoreChannel>) : CoreEvent()
    data class ClientMoved(val clientId: Long, val channelId: Long) : CoreEvent()
    data class TalkStatus(val clientId: Long, val talking: Boolean) : CoreEvent()
    data class Error(val message: String) : CoreEvent()
    // PcmFrame is intentionally not surfaced here — audio I/O is PHA-3077's
    // AudioEngine; the UI only needs talk state, not the samples.
}

data class CoreChannel(
    val id: Long,
    val name: String,
    val parentId: Long?,
    val hasPassword: Boolean,
    val talkPower: Long,
)

interface CoreClient {
    fun connect(address: String, port: Int, nickname: String, identityPem: String, password: String?)
    fun disconnect()
    fun joinChannel(channelId: Long, password: String?)
    fun setInputMuted(muted: Boolean)
    fun setOutputMuted(muted: Boolean)
    fun close()
}

object CoreBridge {
    fun coreVersion(): String = try {
        uniffi.plnt_core.coreVersion()
    } catch (e: Throwable) {
        "unavailable: ${e.javaClass.simpleName}: ${e.message}"
    }

    /** Create a native client. `onEvent` is called from a Rust-owned thread — hop to Main before touching UI state. */
    fun newClient(onEvent: (CoreEvent) -> Unit): CoreClient {
        val sink = object : uniffi.plnt_core.EventSink {
            override fun onEvent(ev: uniffi.plnt_core.ConnEvent) {
                onEvent(translate(ev))
            }
        }
        val native = uniffi.plnt_core.Client(sink)
        return object : CoreClient {
            override fun connect(address: String, port: Int, nickname: String, identityPem: String, password: String?) {
                native.connect(address, port.toUShort(), nickname, identityPem, password)
            }
            override fun disconnect() = native.disconnect()
            override fun joinChannel(channelId: Long, password: String?) =
                native.joinChannel(channelId.toULong(), password)
            override fun setInputMuted(muted: Boolean) = native.setInputMuted(muted)
            override fun setOutputMuted(muted: Boolean) = native.setOutputMuted(muted)
            override fun close() = native.destroy()
        }
    }

    fun createIdentity(): String = uniffi.plnt_core.IdentityObj.create().export()
    fun importIdentity(pem: String): Boolean = try {
        uniffi.plnt_core.IdentityObj.import(pem)
        true
    } catch (e: Throwable) {
        false
    }

    private fun translate(ev: uniffi.plnt_core.ConnEvent): CoreEvent = when (ev) {
        is uniffi.plnt_core.ConnEvent.Connected ->
            CoreEvent.Connected(ev.v1.ownClientId.toLong(), ev.v1.serverName)
        is uniffi.plnt_core.ConnEvent.Disconnected -> CoreEvent.Disconnected(ev.reason)
        is uniffi.plnt_core.ConnEvent.ChannelTree -> CoreEvent.ChannelTree(
            ev.v1.map {
                CoreChannel(
                    id = it.id.toLong(),
                    name = it.name,
                    parentId = it.parentId?.toLong(),
                    hasPassword = it.hasPassword,
                    talkPower = it.talkPower,
                )
            }
        )
        is uniffi.plnt_core.ConnEvent.ClientMoved ->
            CoreEvent.ClientMoved(ev.clientId.toLong(), ev.channelId.toLong())
        is uniffi.plnt_core.ConnEvent.TalkStatus ->
            CoreEvent.TalkStatus(ev.clientId.toLong(), ev.talking)
        is uniffi.plnt_core.ConnEvent.PcmFrame -> CoreEvent.TalkStatus(ev.clientId.toLong(), true)
        is uniffi.plnt_core.ConnEvent.Error -> CoreEvent.Error(ev.v1)
    }
}
