package com.plnt.client

import android.os.Bundle
import android.util.Log
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp

class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        // Load the UniFFI-generated bindings + the plnt_core .so. The bridge
        // file is generated by build.sh via `uniffi-bindgen generate ... --language kotlin`.
        val coreVersion: String = try {
            // The generated class lives at com.plnt.client.plnt.plnt_core and the
            // static initializer System.loadLibrary("plnt_core") handles the .so.
            com.plnt.client.plnt.plnt_core.coreVersion()
        } catch (e: Throwable) {
            Log.e("plnt", "core_version() failed", e)
            "core_version() unavailable: ${e.javaClass.simpleName}: ${e.message}"
        }

        setContent {
            PlntTheme {
                Surface(modifier = Modifier.fillMaxSize(), color = MaterialTheme.colorScheme.background) {
                    CoreVersionScreen(coreVersion)
                }
            }
        }
    }
}

@Composable
fun CoreVersionScreen(version: String) {
    Column(
        modifier = Modifier.fillMaxSize().padding(24.dp),
        verticalArrangement = Arrangement.Center,
        horizontalAlignment = Alignment.CenterHorizontally,
    ) {
        Text("PLNT", style = MaterialTheme.typography.headlineLarge)
        Text("voice-only TeamSpeak client", style = MaterialTheme.typography.bodyMedium)
        androidx.compose.foundation.layout.Spacer(modifier = Modifier.padding(12.dp))
        Text("core_version():", style = MaterialTheme.typography.labelMedium)
        Text(version, style = MaterialTheme.typography.bodySmall)
    }
}

@Composable
fun PlntTheme(content: @Composable () -> Unit) {
    MaterialTheme(content = content)
}

@Preview
@Composable
private fun PreviewCoreVersion() {
    PlntTheme { CoreVersionScreen("plnt-core 0.1.0 (tsclientlib@ee3bc6f)") }
}
